# Generated by Django 4.1.5 on 2023-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fio',
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='project',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Проект сотрудника'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Телеграм'),
        ),
    ]
