# Generated by Django 4.1.5 on 2023-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_news_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
