# Generated by Django 4.1.5 on 2023-06-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_organization_subnet_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
    ]
