# Generated by Django 4.1.5 on 2023-06-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_organization_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='organization_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organizationaddress', verbose_name='Адрес организации'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят')], default='free', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subnet', verbose_name='Подсеть'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='numberhouse',
            field=models.CharField(max_length=50, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_addresses', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица'),
        ),
    ]
