# Generated by Django 4.1.5 on 2023-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaddress',
            name='numberhouse',
            field=models.CharField(max_length=5, verbose_name='Номер дома'),
        ),
    ]
