# Generated by Django 4.1.5 on 2023-06-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_task_deadline_notification_task_reminder_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.news'),
        ),
    ]
